<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-K8DIB7L" failures="1" tests="4" name="staffModule1.ViewCustomerByAccNoTest" time="12.518" errors="0" timestamp="2024-02-29T17:47:29 IST" skipped="2">
  <testcase classname="staffModule1.ViewCustomerByAccNoTest" name="viewActiveCustomer" time="3.845"/>
  <testcase classname="staffModule1.ViewCustomerByAccNoTest" name="viewCustomerByAccNo" time="3.817">
    <skipped/>
  </testcase> <!-- viewCustomerByAccNo -->
  <testcase classname="staffModule1.ViewCustomerByAccNoTest" name="viewCustomerByAccNo" time="2.360">
    <skipped/>
  </testcase> <!-- viewCustomerByAccNo -->
  <testcase classname="staffModule1.ViewCustomerByAccNoTest" name="viewCustomerByAccNo" time="2.496">
    <failure message="null" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at staffModule1.ViewCustomerByAccNoTest.viewCustomerByAccNo(ViewCustomerByAccNoTest.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- viewCustomerByAccNo -->
  <system-out>
    <![CDATA[--Connect to DB
StaffLogin
StaffLogout
StaffLogin
StaffLogout
StaffLogin
StaffLogout
StaffLogin
StaffLogout
Browser Closed
StaffLogin
StaffLogout
StaffLogin
StaffLogout
StaffLogin
StaffLogout
Browser Closed
StaffLogin
Incorrect Account Number
StaffLogout
Browser Closed
StaffLogin
Clicked On Approve Pending Account 
Got Application Number From Excel 
Entered Application Number And Clicked On Search Button
StaffLogout
StaffLogin
Clicked On Approve Pending Account 
Got Application Number From Excel 
Entered Application Number And Clicked On Search Button
StaffLogout
StaffLogin
Clicked On Approve Pending Account 
Got Application Number From Excel 
Entered Application Number And Clicked On Search Button
Write Approved Infornt of Application Number
StaffLogout
StaffLogin
Clicked On Approve Pending Account 
Got Application Number From Excel 
Entered Application Number And Clicked On Search Button
StaffLogout
Browser Closed
StaffLogin
Clicked On Credit Customer Button
Amount credited Successfully to customer account
StaffLogout
Browser Closed
--DisConnect to DB]]>
  </system-out>
</testsuite> <!-- staffModule1.ViewCustomerByAccNoTest -->
